/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package foo;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Bar classUnderTest = new Bar();
        assertTrue("Bar exists", classUnderTest instanceof Bar );
    }
}
