/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package foo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Classic classUnderTest = new Classic();
        assertTrue(classUnderTest instanceof Classic);
    }
}
